"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials
import json

# Load environment variables from .env file 
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize Firebase Admin SDK
# FIREBASE_CREDENTIALS = BASE_DIR / "freelancing-6b4b9-firebase-adminsdk-fbsvc-c42fac3c29.json"
# cred = credentials.Certificate(str(FIREBASE_CREDENTIALS))  # Convert Path object to string

FIREBASE_CREDENTIALS={
  "type": "service_account",
  "project_id": "freelancing-6b4b9",
  "private_key_id": "c42fac3c2954b142c4f01f4a68c014365a8c60aa",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6fbQn+IDfFSfb\nRerTkytM4vP1u3tqHLc5569IvlvHVNlxrJ7FcSba7NLdae4ktu9plqmOPgzjfDOz\nj9Vzxc5SaGaiw5JuVtG2/NzFbc9z2llKbJcgCLH/Fi9xMMiZkP+2OLq3/LenO9ZR\nw6Hris0F4A1i/q9xWk3H4u25xhHYUwdCukqKLNXBi4O8lWcVo+VB2u1XAmjaMS7B\nVZwBaibOiIm+wLlj7pjdmncCp+BH3X4rP/pKjzjiM2/HQ0dF492y854ABmueICr/\nEMgqsaPMcpbv2xCYhnUF4pZ7VePFJE6ApgMkRCkUTFOILKZf+izp1fD2QrAL4v8b\nmz4aZnn3AgMBAAECggEAAuf8Ygng2qXsc5UHP+aeUtOC/fRyGJxVWXBcKAcmmTIg\nAcH9zWtIfqCyXonzXWlOZmsj8RgHDZdJzpJyWJxsbTAituzTGaexTlrQoL3OPeql\n4CxWCvh0hNpv9DsdSfgoMmSq7QmuqpgBOU/4dE1UiZlmvzRJ2dUQh9abYf0NgFbJ\nrUaz1YuObgyiweHj3AyL56Umv+EKpmqyA5UdToO4iVHnNzGO/PrXty0sgYtZUi4i\nzGKthFjpLrFIvFErLcBYsOrERppmQ2qY5KY6J9YSEHpcwX1P5QfSZpZiwe+9kovi\nD5KWGztIcnD583Ms21YNI3mtHH/pW91WV9PTzF3APQKBgQDnvvrXhcDRZBxNW3Yc\nU21jKKiTQPYq9ecHmWenhx1rQuSJRxow8enIcFgT5qw5cZN5u7fWYJQNI0L923U1\nfMxU5o+XG2amgnK/MlwQvds9wpiZD9gw0IThqe5dwwSuBMDrh701BvMcmO5TK4fc\no3WFF7fFK02tUiVK9TEoezoSPQKBgQDOAjyNMwwYappMoi6SY0LTxA7ifPiu0y7l\n/VwyyOZs0+Vww6hKzFlp05TvJiVlO1diBu/c+HzHuzZ4/UzOAHTlGdSZvOAffhJc\nHySpEkrOLQmiRULfMa4/gsJ6qc3vxS/fvMOWVoUkNqFOSSkpD1WjTV03NDQwBqUP\n01pPugHEQwKBgQCxRMo2IE79HNn1ZnfzdPGgvxIsCa4D8LO3gWXjpRwg1ztfsu7a\n78GHnEATgQjOrA1GOgyGxLubTRTKgJuovXzDmNXPnZso1XIWxNvdxoy1Mmxt8MvL\nk0WCJO179VhYELTNtbhKnrVKc8UiA5NaeALGOv1MqjIx2TtDmkjvEUu7dQKBgCQJ\n/h/Rg1cuJworASy40rMLRHNY24RyC21Osndr7+uv8h6VC/bx4t6Bljd0G+ymwfWz\nMvkcO3ARj0kBPxN2vvxpVWkDws2fl4SoKhity4pgFKRfq4AyR8JylKUy2YUNoP9q\nHWlKf4ZDTFrOr7WwKhIkcZ87sbmJIA0xs0XpS2/TAoGBAK6hT8+AJTBMr/MtYb3m\nCkVln2+T0UUaWutcyJRsv+sacjmUZTNe2DxO22HkKanLPI7CJquWbxjFkxmxZDDz\nWoMOnzAwPbJnB8L3Xp/OBHToVGvHbaDhIBcu3n4zCzYiuNjZsOzwbkD0kE4Ffe3h\nAcmPQQxhFnCYKAEf9hqVP54k\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-fbsvc@freelancing-6b4b9.iam.gserviceaccount.com",
  "client_id": "107832241603069771844",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40freelancing-6b4b9.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

cred = credentials.Certificate(FIREBASE_CREDENTIALS)  # Applying dict object here
firebase_admin.initialize_app(cred)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9s6an@gqr)wge9%43-jnzunkhxrws5wl7t24m=h6&9v(@!fql9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'anam014.pythonanywhere.com']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp', 
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True  # For development purposes, adjust as needed for production set false if want to explicitly define.

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),  # 1 day in minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default' : { 
      'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'cnndb'),
        'USER': os.getenv('DB_USER', 'anam'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'anam'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', 3306),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'myapp.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# # Sending sms notification implementaion using sms hub india
# SMS_BASE_URL=  os.getenv('SMS_BASE_URL')
# Sending sms notification implementation using SMS Hub India
SMS_BASE_URL = os.getenv('SMS_BASE_URL')

if not SMS_BASE_URL:
    raise ValueError("SMS_BASE_URL environment variable not set")


# Specify ASGI application for Django Channels
ASGI_APPLICATION = 'myproject.asgi.application'

# Configure Channels layer (use Redis for scaling, but for now use in-memory channel layer)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}



